version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./sukinema-app:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
